apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pacman.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pacman.frontend.labels" $ | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "pacman.frontend.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pacman.frontend.labels" $ | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "pacman.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- include "pacman.podSecurityContext" (dict "root" $ "ctx" .Values.podSecurityContext) | nindent 8 }}
      containers:
        - name: pacman
          image: {{ include "pacman.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            {{- if .Values.roles.enabled }}
            - name: APP_ROLE
              value: web
            - name: SCORE_SERVICE_URL
              value: http://{{ include "pacman.fullname" . }}-score:8080
            - name: USER_SERVICE_URL
              value: http://{{ include "pacman.fullname" . }}-user:8080
            {{- end }}
            {{- include "pacman.dbEnv" . | nindent 12 }}
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 5
          resources: {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: {{- toYaml . | nindent 8 }}
      {{- end }}
