{{- if and (eq .Values.database "mongo") (not .Values.mongo.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pacman.mongo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pacman.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-admin-name:     {{ required "mongo.auth.rootUsername must be set"     .Values.mongo.auth.rootUsername     | quote }}
  database-admin-password: {{ required "mongo.auth.rootPassword must be set"     .Values.mongo.auth.rootPassword     | quote }}
  database-name:           {{ required "mongo.auth.databaseName must be set"     .Values.mongo.auth.databaseName     | quote }}
  database-user:           {{ required "mongo.auth.databaseUser must be set"     .Values.mongo.auth.databaseUser     | quote }}
  database-password:       {{ required "mongo.auth.databasePassword must be set" .Values.mongo.auth.databasePassword | quote }}
{{- end }}
{{- if and (eq .Values.database "postgres") (not .Values.postgres.existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pacman.postgres.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "pacman.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ required "postgres.auth.username must be set" .Values.postgres.auth.username | quote }}
  password: {{ required "postgres.auth.password must be set" .Values.postgres.auth.password | quote }}
  database: {{ required "postgres.auth.database must be set" .Values.postgres.auth.database | quote }}
{{- end }}
